---
title: '
author: 
output:
  pdf_document: default
  html_document:
    df_print: paged
---
```{r}
install.packages("sqldf")
install.packages("moments")
install.packages("sqldf")
install.packages("moments")
```

```{r load packages and set options, include=FALSE}
## loading libraries 

library(tidyverse) 
library(magrittr)
library(knitr)
library(patchwork)
library(moments)
library(dplyr)
library(sqldf)
theme_set(theme_bw())
options(tinytex.verbose = TRUE)
```

```{r load data, echo = FALSE, message = FALSE}
## Reading CSV file

anes <- read_csv("anes_timeseries_2020_csv_20220210.csv")
anes
```

```{r}
## Dataframe for Voted + Not_Voted . However due to Difficulty filter 'not voted' are filtered out completely

df1_Voted_NotVoted <- anes %>%mutate(Voter = case_when(V202109x == 1 ~ 'voted' , 
                                        V202109x == 0 ~ 'not voted'   
                                        ))%>%filter(Voter == "voted" | Voter == "not voted")%>%mutate(Party = case_when(V201228 == 1 ~ "Democrat" ,
                                         V201228 == 2 ~ "Republican",
                                         !V201228 %in% 1:2 & V201230 == 1 ~ "Republican",
                                         !V201228 %in% 1:2 & V201230 == 3 ~ "Democrat"
                                         
                                         ))%>%filter(Party == "Democrat" | Party == "Republican")%>%filter(V202119 %in% 1:5)%>%rename('Difficulty' = V202119)%>%subset(select = c(Voter, Party , Difficulty))

```

```{r}
df1_Voted_NotVoted
```


```{r}
## Not-Voted Voters Difficulty Reasons

df1_Voted_NotVoted_new <- anes %>%mutate(Voter = case_when( 
                                        V202109x == 0 ~ 'not voted'   
                                        ))%>%filter(Voter == "not voted")%>%mutate(Party = case_when(V201228 == 1 ~ "Democrat" ,
                                         V201228 == 2 ~ "Republican",
                                         !V201228 %in% 1:2 & V201230 == 1 ~ "Republican",
                                         !V201228 %in% 1:2 & V201230 == 3 ~ "Democrat"
                                         
                                         ))%>%filter(Party == "Democrat" | Party == "Republican")%>%mutate(Difficulty = case_when( 
                                        V202123 == 1 ~ 'I forgot' ,
                                        V202123 == 2 ~ 'I am not interested' ,
                                        V202123 == 3 ~ 'Too busy' ,
                                        V202123 == 4 ~ 'Did not like the candidates' ,
                                        V202123 == 5 ~ 'I am not registered' ,
                                        V202123 == 6 ~ 'I did not have the correct form of identification' ,
                                        V202123 == 7 ~ 'Out of town' ,
                                        V202123 == 8 ~ 'Sick or disabled' ,
                                        V202123 == 9 ~ 'Transportation' ,
                                        V202123 == 10 ~ 'Bad weather' ,
                                        V202123 == 11 ~ 'The line at the polls was too long' ,
                                        V202123 == 12 ~ ' I was not allowed to vote at the polls, even though I tried' ,
                                        V202123 == 13 ~ ' I requested but did not receive an absentee ballot' ,
                                        V202123 == 14 ~ ' I requested but did not receive an absentee ballot' ,
                                        V202123 == 15 ~ ' I requested but did not receive an absentee ballot' ,
                                        V202123 == 16 ~ ' I requested but did not receive an absentee ballot' ,
                                        V202123 == -1 ~ ' Inapplicable' ,
                                        V202123 == -5 ~ '  Interview breakoff' ,
                                        V202123 == -6 ~ ' No post-election interview' ,
                                        V202123 == -7 ~ ' No post-election data, deleted due to incomplete interview' ,
                                        V202123 == -8 ~ ' Dont know' ,
                                        V202123 == -9 ~ ' Refused' 
                                        
                                        ))%>%filter(V202123 %in% 1:16 | V202123 %in% -5:-9 | V202123 %in% -1 )%>%subset(select = c(Voter, Party , Difficulty , V202123 ))

```

```{r}
## Not-Voted Voters Difficulty Reasons

df1_Voted_NotVoted_new%>%group_by(Party,Voter, V202123)
df1_Voted_NotVoted_new
```

```{r}
## Finding percentage of Not-Voted Voters Difficulty Reasons 

### Democrat People

percent_one_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 1 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_one_Democrat

percent_two_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 2 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_two_Democrat
  
percent_three_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 3 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_three_Democrat

percent_four_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 4 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_four_Democrat

percent_5_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 5 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_5_Democrat

percent_6_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 6 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_6_Democrat

percent_7_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 7 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_7_Democrat

percent_8_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 8 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_8_Democrat

percent_9_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 9 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_9_Democrat

percent_10_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 10 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_10_Democrat

percent_11_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 11 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_11_Democrat

percent_12_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 12 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_12_Democrat

percent_13_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 13 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_13_Democrat

percent_14_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 14 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_14_Democrat

percent_15_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 15 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_15_Democrat

percent_16_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == 16 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_16_Democrat

percent_minus1_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == -1 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_minus1_Democrat

percent_minus5_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == -5 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_minus5_Democrat

percent_minus6_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == -6 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_minus6_Democrat

percent_minus7_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == -7 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_minus7_Democrat

percent_minus8_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == -8 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_minus8_Democrat

percent_minus9_Democrat = sum(with(df1_Voted_NotVoted_new, Party == 'Democrat' & V202123 == -9 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Democrat'  ))
percent_minus9_Democrat

```

```{r}
## Finding percentage of Not-Voted Voters Difficulty Reasons 

### Republican People

percent_one_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 1 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_one_Republican

percent_two_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 2 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_two_Republican
  
percent_three_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 3 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_three_Republican

percent_four_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 4 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_four_Republican

percent_5_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 5 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_5_Republican

percent_6_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 6 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_6_Republican

percent_7_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 7 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_7_Republican

percent_8_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 8 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_8_Republican

percent_9_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 9 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_9_Republican

percent_10_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 10 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_10_Republican

percent_11_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 11 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_11_Republican

percent_12_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 12 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_12_Republican

percent_13_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 13 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_13_Republican

percent_14_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 14 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_14_Republican

percent_15_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 15 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_15_Republican

percent_16_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == 16 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_16_Republican

percent_minus1_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == -1 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_minus1_Republican

percent_minus5_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == -5 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_minus5_Republican

percent_minus6_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == -6 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_minus6_Republican

percent_minus7_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == -7 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_minus7_Republican

percent_minus8_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == -8 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_minus8_Republican

percent_minus9_Republican = sum(with(df1_Voted_NotVoted_new, Party == 'Republican' & V202123 == -9 ))*100/sum(with(df1_Voted_NotVoted_new, Party == 'Republican'  ))
percent_minus9_Republican

```

```{r}
## Non-Voted People dataframe (Democrat+ Republican)

y1 = c('forgot' ,'not interested' ,'Too busy' , 'Didnt like candidates' , 'not registered' , 'no identification form ' ,'Out of town' , 'Sick/disabled' , 'Transportation' ,'Bad weather' , 'polls line long' ,'not allowed vote' , 'no absentee ballot' , 'where to vote?' , 'not knew choices', 'other' , ' Inapplicable' , '  Interview breakoff' , ' No election interview' , 'incomplete interview' ,' Dont know' , ' Refused' )
y2 = c(1.19, 10.44 , 9.25 ,14.62, 10.14 , 3.58, 2.68 , 8.05 , 1.19 , 0.0 , 2.38, 0.59, 1.49, 0.89 , 8.65 , 16.71 , 0.89 , 0 , 0,
       0.0,5.07,2.08 ,   1.82, 5.48, 10.18 ,12.27 ,13.31 ,1.30 , 2.87 ,  8.87 , 1.56 , 0.26 , 2.87 , 1.04 , 1.56 ,1.044 ,6.26 , 21.4 ,0.26 ,   0 ,0,0 , 5.74,1.82)
party = c('Democrat', 'Democrat', 'Democrat', 'Democrat', 'Democrat', 'Democrat' , 'Democrat', 'Democrat', 'Democrat', 'Democrat', 'Democrat', 'Democrat', 'Democrat', 'Democrat', 'Democrat', 'Democrat' , 'Democrat', 'Democrat', 'Democrat', 'Democrat', 'Democrat', 'Democrat',
          'Republican', 'Republican', 'Republican', 'Republican', 'Republican', 'Republican' , 'Republican', 'Republican', 'Republican', 'Republican', 'Republican', 'Republican', 'Republican', 'Republican', 'Republican', 'Republican' , 'Republican', 'Republican', 'Republican', 'Republican', 'Republican', 'Republican')

df1_Voted_NotVoted_new_graph = data.frame(y1,y2, party)
df1_Voted_NotVoted_new_graph
```


```{r}
## Non-Voted People difficulty graphs

p <- ggplot(df1_Voted_NotVoted_new_graph, aes(x = reorder(y1, -y2), y = y2 , fill = party , label = y1))
p <- p  + labs(x = "Respondent's Reasons", y = '% of Non-Voters facing difficulty') + ggtitle("% of 'Non-Voters' by Reasons for Not Voting ")  + geom_col(position = "dodge") + 
    theme(axis.text.x = element_blank(), 
          axis.ticks.x = element_blank()) + geom_text(aes(y = 0), angle = 90, hjust = -.05, size = 3) 
p
```

```{r}
## Finding percentages of Voted People (Democrat + Republican) 

percent_one_Democrat = sum(with(df1_Voted_NotVoted, Party == 'Democrat' & Difficulty == 1 ))*100/sum(with(df1_Voted_NotVoted, Party == 'Democrat'  ))
percent_one_Democrat

percent_two_Democrat = sum(with(df1_Voted_NotVoted, Party == 'Democrat' & Difficulty == 2 ))*100/sum(with(df1_Voted_NotVoted, Party == 'Democrat'  ))
percent_two_Democrat
  
percent_three_Democrat = sum(with(df1_Voted_NotVoted, Party == 'Democrat' & Difficulty == 3 ))*100/sum(with(df1_Voted_NotVoted, Party == 'Democrat'  ))
percent_three_Democrat

percent_four_Democrat = sum(with(df1_Voted_NotVoted, Party == 'Democrat' & Difficulty == 4 ))*100/sum(with(df1_Voted_NotVoted, Party == 'Democrat'  ))
percent_four_Democrat

percent_five_Democrat = sum(with(df1_Voted_NotVoted, Party == 'Democrat' & Difficulty == 5 ))*100/sum(with(df1_Voted_NotVoted, Party == 'Democrat'  ))
percent_five_Democrat

###########

percent_one_Republican = sum(with(df1_Voted_NotVoted, Party == 'Republican' & Difficulty == 1 ))*100/sum(with(df1_Voted_NotVoted, Party == 'Republican'  ))
percent_one_Republican

percent_two_Republican = sum(with(df1_Voted_NotVoted, Party == 'Republican' & Difficulty == 2 ))*100/sum(with(df1_Voted_NotVoted, Party == 'Republican'  ))
percent_two_Republican

percent_three_Republican = sum(with(df1_Voted_NotVoted, Party == 'Republican' & Difficulty == 3 ))*100/sum(with(df1_Voted_NotVoted, Party == 'Republican'  ))
percent_three_Republican

percent_four_Republican = sum(with(df1_Voted_NotVoted, Party == 'Republican' & Difficulty == 4 ))*100/sum(with(df1_Voted_NotVoted, Party == 'Republican'  ))
percent_four_Republican

percent_five_Republican = sum(with(df1_Voted_NotVoted, Party == 'Republican' & Difficulty == 5 ))*100/sum(with(df1_Voted_NotVoted, Party == 'Republican'  ))
percent_four_Republican

#########

sum(with(df1_Voted_NotVoted, Party == 'Democrat' & Difficulty == 1 ))
sum(with(df1_Voted_NotVoted, Party == 'Republican' & Difficulty == 1 ))

sum(with(df1_Voted_NotVoted, Party == 'Democrat' & Difficulty == 2 ))
sum(with(df1_Voted_NotVoted, Party == 'Republican' & Difficulty == 2 ))

sum(with(df1_Voted_NotVoted, Party == 'Democrat' & Difficulty == 3 ))
sum(with(df1_Voted_NotVoted, Party == 'Republican' & Difficulty == 3 ))

sum(with(df1_Voted_NotVoted, Party == 'Democrat' & Difficulty == 4 ))
sum(with(df1_Voted_NotVoted, Party == 'Republican' & Difficulty == 4 ))

sum(with(df1_Voted_NotVoted, Party == 'Democrat' & Difficulty == 5 ))
sum(with(df1_Voted_NotVoted, Party == 'Republican' & Difficulty == 5 ))

```

```{r}
## Voted People Dataframe

y1 = c("Not difficult at all","Little difficult","Moderately difficult","Very difficult","Extremely difficult","Not difficult at all","Little difficult","Moderately difficult","Very difficult","Extremely difficult")
y2 = c(87.95,8.01,2.93,0.63,0.44 , 90.44, 5.7 , 2.14 , 1.03 , 1.03)
party = c('Democrat', 'Democrat', 'Democrat', 'Democrat', 'Democrat', 'Republican' , 'Republican', 'Republican', 'Republican', 'Republican')

df1_Voted_NotVoted_1 = data.frame(y1,y2, party)
df1_Voted_NotVoted_1

```


```{r}
## % of voters facing difficulty at each level for each party

combined_plot1 <- df1_Voted_NotVoted_1 %>%
  ggplot(mapping = aes(x = factor(y1 , levels = c("Not difficult at all","Little difficult","Moderately difficult","Very difficult","Extremely difficult"))  , y = y2 , fill = party))  + geom_col(position = "dodge") + labs(x = "Respondent's Feelings", y = '% of Voters facing difficulty') + ggtitle("% of voters facing difficulty at each level for each party")

combined_plot1
```

```{r}
## Wilcox Test

wilcox.test(df1_Voted_NotVoted$Difficulty~df1_Voted_NotVoted$Party)

```

```{r}
#Practical significance through Biserial correlation test

table = df1_Voted_NotVoted[df1_Voted_NotVoted$Party == 'Democrat' | df1_Voted_NotVoted$Party == 'Republican',]
table
cor.test(table$Difficulty, as.numeric(as.factor(table$Party)), method = 'spearman')
```

```{r}
#Practical significance through Common Language Effect Size

sum(df1_Voted_NotVoted$Party == 'Democrat' & !is.na(df1_Voted_NotVoted$Difficulty), na.rm=T) * sum(df1_Voted_NotVoted$Party == 'Republican' & !is.na(df1_Voted_NotVoted$Difficulty), na.rm=T)
```
```{r}
#Common Language Effect Size

divide_by(4327437,8453700)
```

